# Generated by Django 4.2.5 on 2023-09-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkpictures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="count_likes",
            field=models.IntegerField(default=0),
        ),
    ]
