# Generated by Django 4.2.5 on 2023-10-01 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkpictures", "0004_postreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postreview",
            old_name="post_id",
            new_name="post",
        ),
    ]
