# Generated by Django 4.2.5 on 2023-10-01 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkpictures", "0005_rename_post_id_postreview_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavouritePost",
        ),
    ]
